version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-very-secret-key
      - ALLOWED_DOMAIN=https://yourdomain.com
      - ENCRYPTION_KEY=your-32-url-safe-base64-encryption-key
      - HTTP_USER=admin
      - HTTP_PASS=your_secure_password